CREATE TABLE IF NOT EXISTS users(
  `registerNo` CHAR(9)  NOT NULL,
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `address` VARCHAR(500) NOT NULL,
  `branch` VARCHAR(200) NOT NULL,
  `year` int NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`registerNo`));