
CREATE TABLE IF NOT EXISTS attendance(
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `registerNo` CHAR(9)  NOT NULL,
  `subject` VARCHAR(255) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));